version: '3.4'

services:
  mongo:
    ports: !reset []
  api:
    ports: !reset []
    volumes:
      - ${TRAFFIC_DIR_HOST}/arkime:${TRAFFIC_DIR_DOCKER}:ro
  frontend:
    build:
      context: tulip/frontend
      dockerfile: ../../tulip-override/Dockerfile-frontend-override
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:3000 || exit 1"]
        start_period: 120s
        interval: 60s
        timeout: 30s
        retries: 3
    ports: !reset []
  assembler:
    volumes:
      - ${TRAFFIC_DIR_HOST}/arkime:${TRAFFIC_DIR_DOCKER}:ro
  enricher:
    command: "./enricher -eve ${TRAFFIC_DIR_DOCKER}/suricata_logs/eve.json"
    volumes:
      - ${TRAFFIC_DIR_HOST}:${TRAFFIC_DIR_DOCKER}:ro