version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    env_file:
      - elasticsearch/elasticsearch.env
    environment:
      - "ES_JAVA_OPTS=-Xms${ELASTIC_MEMORY:-4G} -Xmx${ELASTIC_MEMORY:-4G}"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks:
      internal:
  arkime:
    build:
      context: arkime
      dockerfile: Dockerfile-arkime
    ports:
      - "8005:8005"
      # TODO: backup, move behind reverse proxy
    healthcheck:
        test: ["CMD-SHELL", "[[ $(curl --silent localhost:8005) == 'Unauthorized' ]] || exit 1"]
        start_period: 120s
        interval: 60s
        timeout: 30s
        retries: 3
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ${TRAFFIC_DIR_HOST}/arkime:/data:ro
      - ${TRAFFIC_DIR_HOST}/suricata_logs:/eve:ro
    networks:
      internal:
  suricata:
    build:
      context: suricata
      dockerfile: Dockerfile-suricata
    volumes:
      - ${TRAFFIC_DIR_HOST}/suricata:/data:rw
      - ${TRAFFIC_DIR_HOST}/suricata_logs:/eve:rw

networks:
  internal:

#include:
#  - path: tulip/docker-compose.yml
#    env_file:
#      - tulip/.env.example
#      - .env

# docker compose up -d --build
# docker compose up -d --build api

# wsl -d docker-desktop
# sudo sysctl -w vm.max_map_count=262144